#!/bin/bash
# SPDX-FileCopyrightText: 2024 Petros Koutsolampros
#
# SPDX-License-Identifier: GPL-3.0-or-later


set -e

echo "Checking for submodule commits not pushed"
CHNG=$(git submodule foreach --quiet \
  'git merge-base --is-ancestor HEAD origin/main 2>/dev/null || echo "$name"')
if [ ! -z "$CHNG" -a "$CHNG" != " " ]; then
    echo "Submodules not pushed"
    exit 1
else
    echo "Submodules pushed"
fi
