version = 1
SPDX-PackageName = "salatest"
SPDX-PackageSupplier = "Petros Koutsolampros <commits@pklampros.io>"
SPDX-PackageDownloadLocation = "https://github.com/spatialnous/gensalatest"

[[annotations]]
path = [
    ".gitignore",
    ".gitattributes",
    "README.md",
    ".clang-format",
    ".clang-tidy",
    ".gitmodules",
    ".mailmap",
    "ThirdParty/.clang-tidy",
    ".github/FUNDING.yml",
    "REUSE.toml"
    ]
precedence = "aggregate"
SPDX-FileCopyrightText = "Petros Koutsolampros <commits@pklampros.io>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
    "RegressionTest/BaselineBinaries/**",
    "dist/**",
    "docs/**.md",
    "RegressionTest/.gitignore"
    ]
precedence = "aggregate"
SPDX-FileCopyrightText = "depthmap authors"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
    ".travis.yml",
    "ci/.gitattributes",
    "tools/build_image/readme.txt"
    ]
precedence = "aggregate"
SPDX-FileCopyrightText = "Christian Sailer"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
    "RegressionTest/**.json",
    "tools/build_image/Dockerfile"
    ]
precedence = "aggregate"
SPDX-FileCopyrightText = "Christian Sailer, Petros Koutsolampros <commits@pklampros.io>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
    "testdata/**",
    "RegressionTest/expected/**"
    ]
precedence = "aggregate"
SPDX-FileCopyrightText = "Public domain"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "ThirdParty/Catch/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Catch2 Authors"
SPDX-License-Identifier = "BSL-1.0"

[[annotations]]
path = "ThirdParty/FakeIt/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Eran Pe'er"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "docs/Agents_Manual_Draft01_2012.pdf"
precedence = "aggregate"
SPDX-FileCopyrightText = "Kinda Al_Sayed, Alasdair Turner"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "docs/DepthmapManualForDummies-v13.pdf"
precedence = "aggregate"
SPDX-FileCopyrightText = "Akkelies van Nes <a.vannes@tudelft.nl>, Chunyan Song"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "docs/DepthmapManualForDummies_v20_short.pdf"
precedence = "aggregate"
SPDX-FileCopyrightText = "Akkelies van Nes <avn@hvl.no>, Claudia Yamu, Chunyan Song, Abdelbaseer A. Mohamed"
SPDX-License-Identifier = "CC0-1.0"
